apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem

